### ISSUE TITLE
Rotación del personaje con el ratón

### ISSUE THREAD

**Issue by AlbertoGarciaMiguelez** [AlbertoGarciaMiguelez/Practica_Videojuego#15]

**Comment by AlbertoGarciaMiguelez** [comment]
Tiempo Estimado:
5h

**Comment by Ferhandel** [comment]
Tiempo real: 20 minutos

**Comment by AlbertoGarciaMiguelez** [comment]
Problema con el cursor, al iniciar el juego el punto inicial del cursor esta al lateral del personaje en vez de mirar arriba que es lo más natural.
Nombre: Bug Cursor
