### ISSUE TITLE
GDD Implementación de datos

### ISSUE THREAD

**Issue by AlbertoGarciaMiguelez** [AlbertoGarciaMiguelez/Practica_Videojuego#18]
Controles, tipo de enemigo, como disparos, guardar cargar juego, puntuación, nombre del personaje, tipo de arma, objetos, curar, teletransporte, sistema de combate, que hacer para ganar, fotos  de menú nivel armas enemigo(todo), argumento.

**Comment by AlbertoGarciaMiguelez** [comment]
Tiempo Estimado:
15h
Se necesita información por parte de los developers.
Ir dando la información por aquí, gracias.
Tiempo Final 10h

**Comment by Coriantum** [comment]
**Argumento(idea)** --> Joven de 16 años se cuela en una discoteca, al pasar el tiempo se da cuenta de que el ambiente ha cambiado y empiezan a perseguirlo. ¿La razón? Todos se han contagiado de una inédita variante del C*VID-19 llamada Ferocrón, cuyos síntomas son parecidas a la de la rabia o un zombie, con la ligera diferencia de perseguir a aquellas personas que más feromonas producen. El protagonista deberá sobrevivir hasta la llegada de las nuevas vacunas.

**Controles**: 
-ASDW para el movimiento del jugador
- Uso del ratón para la rotación del jugador y disparo

**Tipo de munición:** 
-Elementos de discoteca -> Botellas en un principio(Si tenemos tiempo dispondría de mas elementos)

**Nombre de Personaje(Idea)** -> Ha-neul (Juan para los amigos),la idea es dar algo de comedia al juego

**Objetos** --> No sabremos si tendremos o no, dependerá del tiempo que nos lleve el juego base

**Teletransporte** --> Ya que el juego está inspirado en PAC-MAN, el nivel poseerá 2 puntos de teletransporte de un lugar a otro(Los baños).

**Sistema de combate** --> Survival shooter con vista cenital

**Que hacer para ganar** --> En un principio sería un sistema de oleadas

**Menú de pausa** --> Intentaremos hacerlo

**Guardado** --> No creo que sea necesario si va a ser un juego por oleadas
