### ISSUE TITLE
Developers ramas

### ISSUE THREAD

**Issue by AlbertoGarciaMiguelez** [AlbertoGarciaMiguelez/Practica_Videojuego#28]

**Comment by Ferhandel** [comment]
Ya encontramos la solución. Había que cambiar a mano mis archivos locales del proyecto. 
Los cambios se hicieron en la rama "Diseño_Nivel" y no en la de "Codigo_Personaje"
Pasé la carpeta de la rama "Diseño_Nivel" que si contenía los cambios a mi rama. Ya pude hacer un push.
Ahora estoy teniendo problemas a la hora de hacer el pull request en Github. Algunos archivos de unity estan generando clonficto:  
Conflicting files
Assets/Scenes/SampleScene.unity
Assets/Sprites/HLM1_Sprites/Player/sprEnterWindow_strip14.png.meta
UserSettings/EditorUserSettings.asset

**Comment by Coriantum** [comment]
Solucionado: Comparé las versiones de la rama main con la de Codigo-personaje y al revisar el codigo se han eliminado partes que no eran necesarias o que se repetían.
Esto dio lugar a un pequeño problema: No aparecía el objeto Player,se creó de nuevo junto con su collider y se añadió su Script de movimiento.
