### ISSUE TITLE
Programar IA del enemigo

### ISSUE THREAD

**Issue by AlbertoGarciaMiguelez** [AlbertoGarciaMiguelez/Practica_Videojuego#35]
Hacer que la IA persiga al personaje

**Comment by Coriantum** [comment]
Creado el script(basico) de la IA del enemigo. Es posible su perfeccionamiento.
Falta asignar dicho script al Gameobject "Enemigo"

**Comment by Coriantum** [comment]
Asignados los scripts al prefab "Enemy".
Está surgiendo un problema que esperamos solucionar: Los enemigos quedan colisionando con las paredes por lo que la mecánica aún debe mejorar.

**Comment by Coriantum** [comment]
Solucionado el problema de las colisiones de los enemigos: Se ha recurrido a la herramienta NavMesh de Unity  para establecer por qué zonas deben los enemigos caminar y sortear los colliders.
Problema: dicha herramienta parece estar creada para Unity 3D, por lo que recurrí a un usuario de GitHub que tenía varios scripts que permitía su funcionamiento en ámbito 2D.

Tiempo total dedicado: 5h
