### ISSUE TITLE
Diseño del nivel

### ISSUE THREAD

**Issue by Coriantum** [AlbertoGarciaMiguelez/Practica_Videojuego#9]
Creación básica del nivel, preparada para establecer sus límites y colisiones

**Comment by AlbertoGarciaMiguelez** [comment]
Tiempo estimado:
6h

**Comment by Coriantum** [comment]
Diseño principal del nivel completado. Pendiente de posibles cambios según la jugabilidad y testeo. Tiempo estimado: 4h
